test_register:
    resource: "@TestRegisterBundle/Resources/config/routing.yml"
    prefix:   /
login:
    pattern: /login
    defaults: { _controller: UserUserBundle:Security:login }

login_check:
    pattern: /login_check
    
logout:
    pattern: /logout
    

